project:
  type: website

website:
  title: "Paris 2024 Olympics Medals"
  favicon: images/Paris2024_Mono_Blanc.png
  page-navigation: true
  repo-url: https://github.com/emaleckova/paris-2024-medals
  repo-actions: [edit, source, issue]

format:
  html:
    theme: [vapor, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px