project:
  title: "Dashboard_main"
  type: website

website:
  title: "Paris 2024 Olympics Medals"
  favicon: images/Paris2024_Mono_Blanc.png
  page-navigation: true
  repo-url: https://github.com/emaleckova/paris-2024-medals
  repo-actions: [edit, source, issue]

format:
  html:
    main-font: gowun-dodum
    theme:
      - pulse
      - custom.scss
    #highlight-style: atom-one-dark
    css: 
      - visuals/css/gowun-dodum.css
    toc: true
    grid:
      sidebar-width: 150px

embed-resources: false

filters:
  - shinylive