project:
  type: website

website:
  title: "Paris 2024 Olympics"
  favicon: images/Paris2024_Mono_Blanc.png
  page-navigation: true
  repo-url: https://github.com/emaleckova/paris-2024-medals
  repo-actions: [source, edit, issue]

format:
  html:
    theme:
      - pulse
      - visuals/custom.scss
    #highlight-style: atom-one-dark
    css: 
      - visuals/css/gowun-dodum.css
    grid:
      sidebar-width: 150px
    include-in-header: 
      - text: <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

embed-resources: false