project:
  type: website

website:
  title: "Paris 2024 Olympics"
  favicon: images/Paris2024_Mono_Blanc.png
  page-navigation: true
  repo-url: https://github.com/emaleckova/paris-2024-medals
  repo-actions: [source, edit, issue]

format:
  html:
    theme:
      - pulse
      - visuals/custom.scss
    #highlight-style: atom-one-dark
    css: 
      - visuals/css/gowun-dodum.css
    grid:
      sidebar-width: 150px

embed-resources: false