## ROW: Disciplines with mutli-medalists 

<!-- There are only 17 disciplines where one athlete won at least two medals. This section will focus on them. -->

### COL: Top per discipline (static)

```{r}
#| label: get-top-medalists

### Medals per athelete: totals and by type
medalists_summarized <- medalists_dat |> 
  # keep only medal events
  filter(is_medallist == "True") |> 
  # medals by athlete
  group_by(name, country, country_code, gender, discipline, medal_type) |> 
  summarise(N_of_type = n()) |> 
  group_by(name, country, discipline) |> 
  mutate(N_total = sum(N_of_type)) |> 
  ungroup() |> 
  pivot_wider(id_cols = c(1:5, "N_total"), names_from = "medal_type", values_from = "N_of_type")
```

```{r}
top_disciplines <- sort(unique(medalists_summarized[medalists_summarized$N_total > 1, ]$discipline), decreasing = T)

# Selection of athletes is done by total, which is then broken by medal type

# Start of sorted data frame
medalists_top <- medalists_summarized |> 
  filter(N_total > 1) |> 
  group_by(discipline) |> 
  slice_max(N_total, n = 3, with_ties = T) |> 
  # create a label for plots
  mutate(label = paste0(name, " (", country_code, ") \n ", N_total, " medals")) |> 
  # athelte helper IDs - sorted by total number of medals
  group_by(discipline, name) |> 
  arrange(desc(N_total)) |> 
  # discipline_IDs
  group_by(discipline) |> 
  mutate(discipline_id = cur_group_id() * -1) |> 
  # athlete IDs
  group_by(discipline_id) |> 
  mutate(athlete_ID = 1:n())

# replace NAs with zero for smooth plotting
medalists_top[is.na(medalists_top)] <- 0

# extract discipline names -> axis labels
disciplines <- unique(medalists_top$discipline)
```

<!-- plot by gender as well? -->

```{r}
#| label: figure-medalist-scatterpie

ggplot() +
  geom_scatterpie(data = medalists_top, aes(x = athlete_ID * 3, y = discipline_id * 3, group = name, r = N_total / 4),
                  cols = c("Bronze", "Silver", "Gold")) + 
  scale_fill_manual(values = col_medals) +
  coord_equal() +
  scale_y_continuous(breaks = seq(-3, length(top_disciplines) * -3, -3),
                     labels = rev(top_disciplines)) +
  theme_void() +
  theme(axis.text.y = element_text(face = "bold", hjust = 1),
        legend.position = "none")
```

```{r}
#| include: false
#| execute: false

ls_p_medalists <- list()

for (i in top_disciplines) {
  input <- medalists_top |> 
    filter(discipline == i) |> 
    pivot_longer(cols = c("Gold", "Silver", "Bronze"), values_to = "Count", names_to = "Medal_type") |> 
    # arrange by total number of medals
    arrange(desc(N_total)) |> 
    # as factor is for `facet_wrap` (https://stackoverflow.com/questions/15116081/controlling-order-of-facet-grid-facet-wrap-in-ggplot2)
    mutate(across(label, ~factor(., levels = unique(label))))
  
  # p <- ggplot(data = input, aes(x = "", y = Count, fill = Medal_type)) +
  #   geom_bar(stat = "identity", width = 1) +
  #   scale_fill_manual(values = col_medals) +
  #   facet_wrap(~label, scales = "free", ncol = 6) +
  #   coord_polar(theta = "y", start = 0) +
  #   labs(title = i) +
  #   theme_void() +
  #   theme(plot.title = element_text(hjust = 0.5),
  #         aspect.ratio = 1,
  #         legend.position = "none")
  
  # recover details about individual medals
  p <- medalists_dat |> 
    filter(discipline == i, name %in% input$name) |> 
    left_join(select(input, name, label), by = "name") |> 
    mutate(medal_date = lubridate::ymd(medal_date),
           # this is to have dates on x-axis matching with "medal data points"
           medal_date_label = factor(format(medal_date, "%b %d"))) |> 
    ggplot(aes(x = medal_date_label, y = event)) +
    geom_point(aes(colour = medal_type), size = 1) +
    scale_colour_manual(values = col_medals) +
    facet_wrap(~label, scales = "free", ncol = 5) +
    theme_minimal() +
    theme(axis.title = element_blank(),
          axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
          aspect.ratio = 0.65,
          legend.position = "none")
  
  ls_p_medalists[[i]] <- p
}

```


### COL: Explore top medalists by sport (interactive)

<!-- This is an intercative addition to the summary plot created above. User can select discipline and can then explore athletes. -->
```{r}
#| label: medalists-for-ojs

ojs_define(medalists_top_ojs = medalists_top)
```


```{ojs}
medalists = transpose(medalists_top_ojs)

viewof disciplineDropdown = Inputs.select(
  medalists_top_ojs.map(d => d.discipline),
  {
    label: "Choose a discipline",
    unique: true
}
)
```



<!-- backup code -->

```{r}
# Spots with at least two meadls per athlete
unique(medalists_top[medalists_top$N_total > 1, ]$discipline)

# such athletes
unique(medalists_top[medalists_top$N_total > 1, ]$name)
```

