---
title: "Paris 2024 Medals"
format:
  dashboard:
    logo: images/Paris2024_Mono_Blanc.png
    orientation: rows
---

<!-- H1 = PAGE -->

# About

```{r}
#| context: setup
#| label: r-session

library(htmltools)
library(bslib)
library(bsicons)
library(icons)

library(tidyverse)

library(gt)
```

```{r}
#| label: general-visuals

### Medal colours
col_medals <- c("#FCC65B", "#E5E5E5", "#E0BD95")
names(col_medals) <- c("Gold", "Silver", "Bronze")
```


```{r}
#| label: get-data

### All NOCs
all_noc <- read.delim("data/nocs.csv", sep = ",", header = T)
# These include historical territories as well - exclude them
noc_present <- filter(all_noc, note == "P")

### Participating athletes
athletes_dat <- read.delim("data/athletes.csv", sep = ",", header = T)

### Nations with medals
nations_dat <- read.delim("data/medals_total.csv", sep = ",", header = T)

### Schedule
schedule_dat <- read.delim("data/schedules.csv", sep = ",", header = T)
```

## ROW: NOC value boxes

```{r}
#| label: overview-stats

### AIM: Get NOCs vs qualified vs with at least one medal

# All NOCs
n_noc_all <- nrow(noc_present)

# NOCs qualified
n_noc_qualified <- length(unique(athletes_dat$country_code))

# NOCs with medals
n_noc_medals <- length(unique(nations_dat$country_code))


### AIM: Medal-winning competitions

# Total of medal sets awarded
n_awards <- sum(schedule_dat$event_medal)
```

```{r}
#| context: valuebox-medal-competitions

bslib::value_box(
  title = tags$h3("Medal ceremonies", style = "cont-size: 20px;"),
  #theme = "dash_gold",
  showcase = bs_icon("award-fill"),
  value = tags$p(n_awards, style = "font-size: 42px; font-face: bold;")
)
```

```{r}
#| label: valuebox-all-nocs

bslib::value_box(
  title = tags$h3("Registered NOCs", style = "cont-size: 20px;"),
  #theme = "dash_gold",
  showcase = bs_icon("globe2"),
  value = tags$p(n_noc_all, style = "font-size: 42px; font-face: bold;")
)
```

```{r}
#| context: valuebox-nocs-qual

bslib::value_box(
  title = tags$h3("Qualified NOCs", style = "cont-size: 20px;"),
  #theme = "dash_gold",
  showcase = bs_icon("check2-all"),
  value = tags$p(n_noc_qualified, style = "font-size: 42px; font-face: bold;")
)
```

```{r}
#| context: valuebox-nocs-medals

bslib::value_box(
  title = tags$h3("NOCs with medalists", style = "cont-size: 20px;"),
  #theme = "dash_gold",
  showcase = bs_icon("award"),
  value = tags$p(n_noc_medals, style = "font-size: 42px; font-face: bold;")
)
```

## ROW: Facts about the Games

These are some impressive numbers about the 32^nd^ Summer olympics held in Paris from July 26 to August 11, 2024. The Paris Games were exceptional in many other aspects - let's explore a selection together.    


----------------------------------------------------------------------------------

**Motivation:**  

I made this website to practice use of Quarto dashboards and deployment to public.

----------------------------------------------------------------------------------



<!-- -------- -->
<!-- New page -->

# Top nations

{{< include _TopNations.qmd >}}

# Top medallists

{{< include _TopMedallists.qmd >}}




